# Code generated by Morphe
# Source: Morphe Registry

# Code generated by Morphe
# Entity DTO (Data Transfer Object)
# Note: Entities are DTOs/ViewModels, not SQLAlchemy ORM models

from typing import List, Optional, TYPE_CHECKING

if TYPE_CHECKING:
    from .person import Person

class Company:
    """
    Company entity.

    Identifiers: 1
    Relationships: 1
    """
    # primary identifier
    id_: int
    name: str
    tax_id: Optional[str] = None
    persons: List[Person] = None

    def get_id(self) -> str:
        """Get the primary identifier."""
        return self.id

    async def load_persons(self) -> List['Person']:
        """Load related Person entities."""
        # TODO: Implement lazy loading
        return []