# Code generated by Morphe
# Source: Morphe Registry

from enum import Enum


class Nationality(Enum):
    """Nationality enumeration."""
    DE = "German"
    FR = "French"
    US = "American"

    @classmethod
    def from_value(cls, value):
        """Get enum member from value."""
        for member in cls:
            if member.value == value:
                return member
        raise ValueError(f"No Nationality member with value {value}")