# Code generated by Morphe
# Source: Morphe Registry

from enum import Enum


class UniversalNumber(Enum):
    """UniversalNumber enumeration."""
    EULER = 2.7182818285
    PI = 3.1415926535

    @classmethod
    def from_value(cls, value):
        """Get enum member from value."""
        for member in cls:
            if member.value == value:
                return member
        raise ValueError(f"No UniversalNumber member with value {value}")