# Code generated by Morphe
# Source: Morphe Registry

# Code generated by Morphe
# SQLAlchemy model definition
# Note: This requires a Base class defined as:
#   from sqlalchemy.ext.declarative import declarative_base
#   Base = declarative_base()

from .base import Base
from sqlalchemy import Column, Integer, String, Text, Float, Boolean, DateTime, Date, ForeignKey, JSON, relationship
from typing import List, Optional, TYPE_CHECKING

if TYPE_CHECKING:
    from .person import Person

class Company(Base):
    __tablename__ = 'company'

    """Company model."""
    id_ = Column(Integer, primary_key=True, autoincrement=True)
    name = Column(String, nullable=False)
    tax_id = Column(Integer, ForeignKey('tax.id'), nullable=False)

    person = relationship("Person", back_populates="company")