# Code generated by Morphe
# Source: Morphe Registry

# Code generated by Morphe
# SQLAlchemy model definition
# Note: This requires a Base class defined as:
#   from sqlalchemy.ext.declarative import declarative_base
#   Base = declarative_base()

from .base import Base
from sqlalchemy import Column, Integer, String, Text, Float, Boolean, DateTime, Date, ForeignKey, JSON, relationship
from typing import Optional, TYPE_CHECKING

if TYPE_CHECKING:
    from .person import Person

class ContactInfo(Base):
    __tablename__ = 'contact_info'

    """ContactInfo model."""
    email = Column(String, nullable=False)
    id_ = Column(Integer, primary_key=True, autoincrement=True)
    person_id = Column(Integer, ForeignKey('person.id'), nullable=False)

    person = relationship("Person", back_populates="contact_info")