# Code generated by Morphe
# Source: Morphe Registry

from pydantic import BaseModel
from typing import Optional, Union, TYPE_CHECKING

if TYPE_CHECKING:
    from .company import Company
    from .person import Person

class Comment(BaseModel):
    """Comment model."""
    content: str
    id: int
    commentable_type: Optional[str] = None
    commentable_id: Optional[str] = None
    commentable: Optional[Union['Person', 'Company']] = None