# Code generated by Morphe
# Source: Morphe Registry

from pydantic import BaseModel
from typing import Optional, TYPE_CHECKING

if TYPE_CHECKING:
    from .person import Person

class Contact(BaseModel):
    """Contact model."""
    email: str
    id: int
    phone: str
    person_id: Optional[str] = None
    person: Optional['Person'] = None

    model_config = {
        "validate_assignment": True,
        "use_enum_values": True,
    }