# Code generated by Morphe
# Source: Morphe Registry

from pydantic import BaseModel
from typing import Optional, List, TYPE_CHECKING

if TYPE_CHECKING:
    from .comment import Comment
    from .contact import Contact

class Person(BaseModel):
    """Person model."""
    id: int
    name: str
    comments: Optional[List[Comment]] = None
    contact_info: Optional['Contact'] = None

    model_config = {
        "validate_assignment": True,
        "use_enum_values": True,
    }