# Code generated by Morphe
# Source: Morphe Registry

# Code generated by Morphe
# Structure DTO (Data Transfer Object)

from typing import Optional


class Address:
    """Address data transfer object."""
    city: str
    house_nr: str
    street: str
    zip_code: str