# Code generated by Morphe
# SQLAlchemy Base definition

from sqlalchemy.ext.declarative import declarative_base

# Create the declarative base that all models will inherit from
Base = declarative_base()

# You can customize the Base class here if needed
# For example:
# Base.query = db.session.query_property()

