# Code generated by Morphe
# Source: Morphe Registry

from enum import Enum


class CommentType(Enum):
    """CommentType enumeration."""
    INTERNAL = "INTERNAL"
    PRIVATE = "PRIVATE"
    PUBLIC = "PUBLIC"

    @classmethod
    def from_value(cls, value):
        """Get enum member from value."""
        for member in cls:
            if member.value == value:
                return member
        raise ValueError(f"No CommentType member with value {value}")